# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty



# Setup
title:               Exnora Green Pammal
tagline:             'For stree bin-free and litter-free India'
description:         'Exnora Green Pammal works with the private sector to minimize waste and pollution..'
url:                 https://greenpammal.github.io/greenpammalin
baseurl:             '/greenpammalin'
paginate:            1

# About/contact
author:
  name:              Mrs. Mangalam Balasubramanian
  url:               http://www.greenpammal.in
  email:             mangalam.b@gmail.com


